name: Build Tauri (Windows)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'src-tauri/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'package-lock.json'
      - 'yarn.lock'
      - 'next.config.*'
      - 'src/**'

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      NODE_OPTIONS: --max-old-space-size=4096
      NEXT_TELEMETRY_DISABLED: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Rust (stable MSVC)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Build Tauri (Windows)
        run: npx tauri build

      - name: Upload bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauri-windows-bundle
          path: |
            src-tauri/target/release/bundle/**
          if-no-files-found: warn
